golosovalka/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'polls'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^register/$', views.RegisterFormView.as_view(), name='register'),
	url(r'^questions/$', views.QuestionListView.as_view(), name='questions'),
	url(r'^myquestions/$', views.MyQuestionListView.as_view(), name='myquestions'),
	url(r'^question/(?P<pk>\d+)/$', views.check_vote, name='detail'),
	url(r'^question/(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
	url(r'^question/(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
	url(r'^statistic/$', views.stat_view, name='statistic'),
    url(r'^question/create/$', views.QuestionCreate.as_view(), name='question_create'),
    url(r'^question/(?P<pk>\d+)/update/$', views.QuestionUpdate.as_view(), name='question_update'),
    url(r'^question/(?P<pk>\d+)/delete/$', views.QuestionDelete.as_view(), name='question_delete'),
    url(r'^choice/create/$', views.ChoiceCreate.as_view(), name='choice_create'),
    url(r'^choice/(?P<pk>\d+)/update/$', views.ChoiceUpdate.as_view(), name='choice_update'),
    url(r'^choice/(?P<pk>\d+)/delete/$', views.ChoiceDelete.as_view(), name='choice_delete'),
]

practice/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('golosovalka/', include('golosovalka.urls')),
    path('', RedirectView.as_view(url='/golosovalka/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
]

golosovalka/models.py
from django.contrib.auth.models import User
from django.urls import reverse
from django.db import models
import datetime
import django.utils.timezone as tnow
def user_directory_path():
	return 'polls/'


class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published',default=tnow.now()) #datetime.datetime.now()
	upload = models.ImageField(upload_to='polls/',default='polls/def_img.png')
	users = models.ManyToManyField(User, help_text="Users who vote",blank=True)
	def was_published_recently(self):
		#now = datetime.datetime.now()
		#return now - datetime.timedelta(days=1) <= self.pub_date <= now
		return True
	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently?'
	def __str__(self):
		return self.question_text
	def get_absolute_url(self):
		return reverse('polls:detail', args=[str(self.id)])
	class Meta:
		ordering = ["-pub_date"]
		permissions = (("can_create_qc", "Create question and choices"),)  

class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	def __str__(self):
		return self.choice_text
	def vcount(self):
		return self.votes

golosovalka/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import get_object_or_404
from django.views.generic.edit import FormView
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from .models import Question, Choice
from django.shortcuts import render
from django.core.files import File
from django.forms import ModelForm
from django.views import generic
from django.urls import reverse
import datetime

def index(request):
	model = Question
	# Генерация "количеств" некоторых главных объектов
	num_questions=Question.objects.all().count()
	num_votes = 0
	
	for i in Choice.objects.all():
		num_votes+=i.votes
	#num_votes=Question.objects.all().count()
	# Доступные книги (статус = 'a')
	#num_instances_available=BookInstance.objects.filter(status__exact='a').count()
	#num_authors=Author.objects.count()  # Метод 'all()' применен по умолчанию.
	return render(
		request,
		'index.html',
		context={
			'num_questions':num_questions,
			'num_votes':num_votes,
			},)

class RegisterFormView(FormView):
	form_class = UserCreationForm
	success_url = '/'
	
	template_name = "golosovalka/register.html"
	
	def form_valid(self, form):
		form.save()
		return super(RegisterFormView, self).form_valid(form)
	
	def form_invalid(self, form):
		form.save()
		return super(RegisterFormView, self).form_invalid(form)

# ~ class PollForm(ModelForm):
    # ~ class Meta:
        # ~ model = Question

# ~ class QuestionCreate(CreateView):
	# ~ def post(self, request, *args, **kw):
		# ~ form = PollForm(request.POST)
		# ~ if form.is_valid():
			# ~ app = form.save()
			# ~ return HttpResponseRedirect(reverse('polls:question', args=(app.id,)))
		# ~ else:
			# ~ return super(CreateAppView, self).post(request, *args, **kw)

class QuestionCreate(CreateView):
	model = Question
	fields = ['question_text','pub_date','upload']
	initial = {'pub_date': datetime.datetime.now(),}

class QuestionUpdate(UpdateView):
	model = Question
	fields = []

class QuestionDelete(DeleteView):
	model = Question
	success_url = reverse_lazy('polls:questions')

class ChoiceCreate(CreateView):
	model = Choice
	fields = ['question','choice_text']
	initial = {'pub_date': datetime.datetime.now(),}

class ChoiceUpdate(UpdateView):
	model = Choice
	fields = ['question','choice_text']

class ChoiceDelete(DeleteView):
	model = Choice
	success_url = reverse_lazy('polls:questions')

class QuestionListView(generic.ListView):
	model = Question
	paginate_by = 10
	def get_context_data(self, **kwargs):
		# В первую очередь получаем базовую реализацию контекста
		context = super(QuestionListView, self).get_context_data(**kwargs)
		return context

class MyQuestionListView(LoginRequiredMixin,generic.ListView):
	model = Question
	template_name ='golosovalka/myquestions.html'
	paginate_by = 10
	
	def get_queryset(self):
		return Question.objects.all().order_by('pub_date')

class ResultsView(generic.DetailView):
	model = Question
	template_name = 'golosovalka/results.html'

class StatisticView(generic.DetailView):
	model = Question
	template_name = 'golosovalka/results.html'

def check_vote(request,pk):
	question = get_object_or_404(Question, pk=pk)
	usr = request.user
	if (usr in question.users.all()):
		return HttpResponseRedirect(reverse('polls:results', args=(pk,)))
	else:
		return render(request, 'golosovalka/detail.html', {'question': question,})

def stat_view(request):
	q = Question.objects.all()
	vmin = 0
	vmax = 0
	tmin = ''
	tmax = ''
	qu = q[0]
	for i in q:
		clist = i.choice_set.all()
		vlist = {}
		for j in clist:
			vlist.update({j.choice_text:j.votes})
		vlist = sorted(vlist.items(), key=lambda x: x[1], reverse=True)
		if (vlist[0][1]>vmax):
			qu = i
			vmax = vlist[0][1]
			tmax = vlist[0][0]
			vmin = vlist[-1][1]
			tmin = vlist[-1][0]
	return render(request, 'golosovalka/stat.html', {'question': qu,'vmin':vmin,'vmax':vmax,'tmax':tmax,'tmin':tmin})


def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	usr = request.user
	if (usr in question.users.all()):
		# ~ print(request.user)
		# ~ print(question.users.all())
		# ~ print("IN")
		#return render(request,'golosovalka/results.html','question',question) #render(request, 'golosovalka/vote.html', {'question': question,'error_message': "You are already vote",})
		return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
		selected_choice.votes += 1
		selected_choice.save()
		question.users.add(usr)
		return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
	except (KeyError, Choice.DoesNotExist):
		# Redisplay the question voting form.
		return render(request, 'golosovalka/vote.html', {
			'question': question,
			'error_message': "You didn't select a choice.",
		})

golosovalka/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans" />
  <!-- Добавление дополнительного статического CSS файла -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav menu">
          <li><a href="{% url 'polls:index' %}">Home</a></li>
          <li><a href="{% url 'polls:questions' %}">All Questions</a></li>
          <br/>
          {% if user.is_authenticated %}
			 <li><a>User: {{ user.get_username }}</a></li>
			 <li><a href="{% url 'polls:statistic' %}">Statistic</a></li>
			 <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>   
		   {% else %}
			 <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
			 <li><a href="{% url 'polls:register'%}">Register</a></li>
		   {% endif %} 
      </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}
      
      {% block pagination %}
		  {% if is_paginated %}
			  <div class="pagination">
				  <span class="page-links">
					  {% if page_obj.has_previous %}
						  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
					  {% endif %}
					  <span class="page-current">
						  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
					  </span>
					  {% if page_obj.has_next %}
						  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
					  {% endif %}
				  </span>
			  </div>
		  {% endif %}
		{% endblock %}
      </div>
    </div>

  </div>
</body>
</html>

golosovalka/templates/golosovalka/choice_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

golosovalka/templates/golosovalka/detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>{{ question.question_text }}</h1>
<img src="/static/uploads/{{ question.upload.url }}" style='height:200px;width:auto;padding:10px;'>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>
{% endblock %}

golosovalka/templates/golosovalka/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Statistic</h1>

  <p>The project has the following record counts:</p>
  <ul>
    <li><strong>Questions:</strong> {{ num_questions }}</li>
    <li><strong>Votes:</strong> {{ num_votes }}</li>
  </ul>


{% endblock %}

golosovalka/templates/golosovalka/question_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post" style='margin-top:40px;'>
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

golosovalka/templates/golosovalka/question_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Questions List</h1>

    {% if question_list %}
    <div style='display:flex;flex-direction:column;justify-content:center;'>

      {% for poll in question_list %}
        <a class='post' href="{{ poll.get_absolute_url }}">
        <div style='display:flex;width:auto;height:200px; padding:20px;margin-bottom:10px;'>
			<img src="/static/uploads/{{ poll.upload.url }}" style='height:80%;width:auto;padding:10px;'>
			 <span style='padding:10px;'> {{ poll.question_text }}  ({{ poll.pub_date }})</span>
		</div>
		</a>
		<hr>
      {% endfor %}

    </div>
    {% else %}
      <p>There are no books in the library.</p>
    {% endif %}       
{% endblock %}

golosovalka/templates/golosovalka/register.html
{% block title %}Sign Up{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

golosovalka/templates/golosovalka/results.html
{% extends "base_generic.html" %}

{% block content %}
<style>
.main_block{width:80%;margin:0 auto; border: 1px solid black;margin-top:100px}
</style>
<div class='main_block'>
<h1>{{ question.question_text }}</h1>
<img src="/static/uploads/{{ question.upload.url }}" style='height:200px;width:auto;padding:10px;'>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>
</div>
{% endblock %}

golosovalka/templates/golosovalka/stat.html
{% extends "base_generic.html" %}

{% block content %}
<h1>{{ question.question_text }}</h1>
<img src="/static/uploads/{{ question.upload.url }}" style='height:200px;width:auto;padding:10px;'>
<p><span>max -- {{ tmax }} -- {{vmax}}</span></p>
<p><span>min -- {{ tmin }} -- {{vmin}}</span></p>

{% endblock %}

golosovalka/templates/golosovalka/vote.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ question.title }}</h1>
	{% if error_message %}
		<p><strong>{{ error_message }}</strong></p>
	{% else %}
		<form action="{% url 'polls:vote' question.id %}" method="post">{% csrf_token %}
			{% for choice in question.choice_set.all %}
				<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
				<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
			{% endfor %}
			<input type="submit" value="Vote">
		</form>
	{% endif %}
  

{% endblock %}

golosovalka/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Statistic</h1>

  <p>The project has the following record counts:</p>
  <ul>
    <li><strong>Questions:</strong> {{ num_questions }}</li>
    <li><strong>Votes:</strong> {{ num_votes }}</li>
  </ul>


{% endblock %}